apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: bedrock-chat-v2
type: Opaque
stringData:  # Use stringData instead of data
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
