apiVersion: apps/v1
kind: Deployment
metadata:
  name: bedrock-service
  namespace: bedrock-chat-v2
  labels:
    app: bedrock-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bedrock-service
  template:
    metadata:
      labels:
        app: bedrock-service
    spec:
      imagePullSecrets:
        - name: docker-hub-secret
      containers:
        - name: bedrock-service
          image: samitsinghhh/bedrock-service:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: http
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: AWS_REGION
            - name: GO_ENV
              value: "production"
            # Add database connection from configmap
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DATABASE_URL
          # Increase timeouts for AWS initialization
          startupProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 90    # Increased for AWS connection
            periodSeconds: 15
            timeoutSeconds: 15
            successThreshold: 1
            failureThreshold: 20       # More retries for AWS setup
          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 180   # Much longer for AWS initialization
            periodSeconds: 30
            timeoutSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 120   # Longer for AWS ready check
            periodSeconds: 15
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              memory: "256Mi"          # Increased for AWS SDK
              cpu: "200m"
            limits:
              memory: "512Mi"          # More memory for Bedrock
              cpu: "500m"
